INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Minh Long Trading Co.', N'Supplier', N'574.896.1717', N'xjohns@kim.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'VietNet Telecom', N'Supplier', N'001-903-745-6722', N'ryan82@davis.org');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'An Phat Packaging', N'Supplier', N'720.936.9286x3427', N'wmartin@evans.org');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Thanh Cong Tax Agency', N'Supplier', N'+1-779-634-9947x48179', N'hpeterson@frank.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Bao Viet Insurance', N'Supplier', N'578.537.0610', N'jturner@wilson.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Green Leaf Office Store', N'Supplier', N'001-195-510-7793x8513', N'williamwalker@green-patel.biz');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Mai Lan Nguyen', N'Staff', N'588.711.4982x922', N'andrewcooper@lopez-snow.info');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Tuan Anh Tran', N'Staff', N'(893)289-5770', N'richardlyons@gmail.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Lan Phuong Vo', N'Staff', N'524-312-9913x536', N'danamunoz@middleton.biz');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Quang Huy Pham', N'Staff', N'(993)320-1567', N'parkerjonathan@brown.biz');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Diep Chau Le', N'Staff', N'(482)547-7156x67990', N'melaniehill@kelly.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Bao Chau Nguyen', N'Staff', N'6616175737', N'makaylacampbell@hotmail.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'ABC Retail Co.', N'Customer', N'835-230-6223x5766', N'gmorgan@valencia-carpenter.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Blue Ocean Ltd.', N'Customer', N'497-795-2148x7391', N'michael43@scott-kelly.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Speedy Services', N'Customer', N'+1-945-679-3985x244', N'mark44@robinson.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'GoGreen Solutions', N'Customer', N'+1-470-006-2492x906', N'woodjason@robertson.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'VietBiz Technologies', N'Customer', N'(729)772-3398x858', N'williamsmiranda@stone.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Hoang Minh Corp.', N'Customer', N'487.319.7355', N'kmatthews@jones.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Sakura Ventures', N'Customer', N'738-081-5854x89248', N'tmiller@carey.com');
INSERT INTO BussinessPartner (PartnerName, PartnerType, Phone, Email) VALUES (N'Nam An Group', N'Customer', N'001-898-940-9938x5251', N'christopherrobertson@meyer-aguilar.com');